# Guard Configuration

# 消息前缀
message-prefix: "§8[§bGuard§8] §7"

# 白名单设置
whitelist:
  # 白名单列表获取方式 (config 或 database)
  source: "config"
  # 是否启用白名单
  enabled: false
  # 白名单玩家列表
  players:
    - "Player1"
    - "Player2"

# 数据库配置 (用于白名单)
database:
  host: "localhost"
  port: 3306
  database: "guard"
  username: "root"
  password: "password"
  table: "whitelist"

# 功能开关
features:
  # 是否允许生物生成
  creature-spawn: false
  # 是否允许破坏方块
  block-break: false
  # 是否允许放置方块
  block-place: false
  # 是否允许玩家受到伤害
  player-damage: false
  # 是否启用饥饿度
  hunger: false
  # 是否允许丢弃物品
  item-drop: false
  # 是否允许拾取物品
  item-pickup: false
  # 是否在加入时设置为冒险模式
  adventure-on-join: true
  # 是否在加入时清空背包
  clear-inventory-on-join: true

# 消息设置
messages:
  # 加入消息 (%player% 将被替换为玩家名)
  join: "%prefix%§a%player% 加入了游戏！"
  # 离开消息 (%player% 将被替换为玩家名)
  quit: "%prefix%§c%player% 离开了游戏！"
  # 无权限提示
  no-permission: "%prefix%§c你没有权限执行此操作！"
  # 重载成功提示
  reload-success: "%prefix%§a配置重载成功！"
  # 无法破坏方块的提示
  no-break: "%prefix%§c你不能破坏方块！"
  # 无法放置方块的提示
  no-place: "%prefix%§c你不能放置方块！"
  # 无法丢弃物品的提示
  no-drop: "%prefix%§c你不能放置方块！"
  # 无法拾取物品的提示
  no-pickup: "%prefix%§c你不能拾取物品！"
  # 命令相关消息
  usage: "%prefix%§c用法: /guard reload"
  # 白名单相关消息
  not-whitelisted: |
    %prefix%§c你不在服务器白名单内！
    请联系管理员以获取访问权限。
    感谢您的理解！
